[package]
name = "proton-pass-common"
version = "0.8.2"
edition = "2021"

[lib]
doctest = false

[dependencies]
proton-pass-derive = { path = "../proton-pass-derive" }

async-trait = "0.1.74"
coset = "0.3.5"
email_address = "0.2.4"
getrandom = { version = "0.2.10", features = ["js"] }
lazy_static = "1.4.0"
luhn = "1.0.1"
passkey = "0.3.0"
passkey-authenticator = { version = "0.3.0", features = ["testable"] }
passkey-types = { version = "0.3.0", features = ["serialize_bytes_as_base64_string"] }
passwords = "3.1.16"
public-suffix = "0.1.2"
rand = "0.8.5"
regex-lite = "0.1.5"
rmp-serde = "1.1.2"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.111"
serde-querystring = "0.2.1"
totp-rs = "5.4.0"
url = "2.4.1"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
tokio = { version = "1.36", features = ["rt"]}

[[bench]]
name = "card_detector"
harness = false

[[bench]]
name = "password_scorer"
harness = false
