[package]
name = "proton-pass-common"
version = "0.14.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
proton-pass-derive = { path = "../proton-pass-derive" }
proton-pass-totp = { path = "../proton-pass-totp" }

async-trait = "0.1.74"
coset = "0.3.8"
email_address = "0.2.9"
file-format = { version = "0.26.0", features = ["reader"] }
getrandom = { version = "0.3.1", features = ["wasm_js"] }
lazy_static = "1.5.0"
luhn = "1.0.1"
passkey = "0.4.0"
passkey-authenticator = { version = "0.4.0", features = ["testable"] }
passkey-types = { version = "0.4.0", features = ["serialize_bytes_as_base64_string"] }
public-suffix = "0.1.2"
rand = "0.9.0"
regex-lite = "0.1.5"
rmp-serde = "1.1.2"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.111"
url = "2.5.4"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
tokio = { version = "1.36", features = ["rt"]}

[[bench]]
name = "card_detector"
harness = false

[[bench]]
name = "password_scorer"
harness = false
