[package]
name = "proton-pass-mobile"
version = "0.8.3"
edition = "2021"

# Flags for cargo-release
[package.metadata.release]
pre-release-replacements = [
    # Yes, we are relying on the number of whitespaces
    {file="android/lib/build.gradle.kts", search="    version = .*", replace="    version = \"{{version}}\""}
]


[lib]
doctest = false
crate-type = ["cdylib", "staticlib"]
name = "proton_pass_common_mobile"

[dependencies]
proton-pass-common = { path = "../proton-pass-common" }
tokio = { version = "1.36", features = ["full"] }
uniffi = { version = "0.26.1" }

[build-dependencies]
uniffi = { version = "0.26.1", features = [ "build" ] }

[[bin]]
name = "uniffi-bindgen"
path = "./bindgen.rs"
required-features = [ "uniffi/cli" ]
